### ISSUE TITLE
colors are not changing 

### ISSUE THREAD

**Issue by ezoteriusz** [AgitoReiKen/vstheme-zero#1]
![image](https://user-images.githubusercontent.com/72603205/184505627-782016ab-ec57-47b9-96f9-9a88d3db2b73.png)
![image](https://user-images.githubusercontent.com/72603205/184505638-6ff23a4b-9ce2-43ef-9bbe-7801adddf93d.png)
I restarted visual studio and still doesn't work

**Comment by shinyazure** [comment]
@ezoteriusz how did you fix it? or is it still broken for you
im running into the same issue

**Comment by AgitoReiKen** [comment]
> @ezoteriusz how did you fix it? or is it still broken for you im running into the same issue

Tbh, by looking at his screenshot i can't tell what issue he ran to.
But if i'd get this, i would try to check if my intellisense is working. This is an example of what i see when its not yet parsed the file
![image](https://user-images.githubusercontent.com/42333163/187517274-1596cd74-07c0-4686-881a-fb2d7b926075.png)

**Comment by shinyazure** [comment]
I literally just updated VS to 17.3.3 and it worked instantly so thats good
