### ISSUE TITLE
Map mode Scroll Bar is not highlighting current area.

### ISSUE THREAD

**Issue by AntiHeadshot** [AgitoReiKen/vstheme-zero#3]
![image](https://user-images.githubusercontent.com/6231826/212691917-6d998092-b5c0-4978-9667-d7aaaa9bd79e.png)

The current area is not displayed on the scroll bar if in map mode.

**Comment by AgitoReiKen** [comment]
I'll check.

**Comment by AgitoReiKen** [comment]
Seems that's it. 
I'll leave issue open for you to provide feedback

**Comment by AntiHeadshot** [comment]
Thanks! Especially for the super fast response.
